{"name": "Авторизация с неправильным логином", "status": "passed", "description": "Проверка, что с несуществующим логином возвращается ошибка 404", "steps": [{"name": "Логин курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'wronglogin123456', 'password': 'alhrxrpoou'}"}], "start": 1761487113718, "stop": 1761487117411}], "start": 1761487113718, "stop": 1761487117412, "uuid": "a19d9dee-9da5-4821-9bc8-a4e1e1a6ed7b", "historyId": "51d9192c7b4e488100b0b5541e6e113a", "testCaseId": "51d9192c7b4e488100b0b5541e6e113a", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_with_wrong_login_fails", "labels": [{"name": "suite", "value": "Логин курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "Astti-Legion"}, {"name": "thread", "value": "132044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}