{"name": "Авторизация без поля password", "status": "passed", "description": "Проверка, что без password запрос возвращает ошибку 400", "steps": [{"name": "Логин курьера", "status": "broken", "statusDetails": {"message": "requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='qa-scooter.praktikum-services.ru', port=443): Read timed out. (read timeout=10)\n", "trace": "  File \"/Users/kostya/PycharmProjects/Sprint7/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/kostya/PycharmProjects/Sprint7/api/courier_api.py\", line 31, in login_courier\n    return requests.post(COURIER_LOGIN, json=payload, timeout=10)\n  File \"/Users/kostya/PycharmProjects/Sprint7/venv/lib/python3.10/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"/Users/kostya/PycharmProjects/Sprint7/venv/lib/python3.10/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/Users/kostya/PycharmProjects/Sprint7/venv/lib/python3.10/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Users/kostya/PycharmProjects/Sprint7/venv/lib/python3.10/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Users/kostya/PycharmProjects/Sprint7/venv/lib/python3.10/site-packages/requests/adapters.py\", line 532, in send\n    raise ReadTimeout(e, request=request)\n"}, "parameters": [{"name": "payload", "value": "{'login': 'hhqboiprku'}"}], "start": 1761160454302, "stop": 1761160464982}], "attachments": [{"name": "Баг сервиса", "source": "8350399a-991c-409b-89fc-e7ddfc9cfa8e-attachment.txt", "type": "text/plain"}], "start": 1761160454302, "stop": 1761160464996, "uuid": "9620bf63-8813-4cdb-96e3-041a3423b6e7", "historyId": "36c66187d279e2cd63e9b7521c9f8cce", "testCaseId": "36c66187d279e2cd63e9b7521c9f8cce", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_without_password_fails", "labels": [{"name": "suite", "value": "Логин курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "MacBook-Air-Konstantin.local"}, {"name": "thread", "value": "29488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}], "links": [{"type": "issue", "url": "BUG-001", "name": "Баг: API уходит в таймаут при отсутствии password"}]}